name: Andre Ferreira
# avatar: images/profile.png # Avatar image. Default to "images/profile.webp".
bio: 'Fixed Income Trader, Engenheiro.'
#company: Company # HTML markup are supported, such as: <a href="https://example.com" target="_blank" rel="noopener noreferrer">Company</a>.
location: SÃ£o Paulo, Brazil. # HTML markup are supported, such as: <a href='https://www.openstreetmap.org/search?query=Earth'>Earth</a>.
# about: https://razonyang.com # The external about page. The internal about page will be used if not set.
params: {
  # layout: compact
}
social:
  email: teste#gmail.com
  github: github.com/andrefpoli
  twitter: YoloCap_
  #patreon: razonyang
  #paypal: razonyang
  rss: "" # Remove RSS
